/* tslint:disable */
/* eslint-disable */
/**
 * chicken-data API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EggEventOutput
 */
export interface EggEventOutput {
    /**
     * 
     * @type {number}
     * @memberof EggEventOutput
     */
    id: number;
    /**
     * 
     * @type {number}
     * @memberof EggEventOutput
     */
    amount: number;
    /**
     * 
     * @type {Date}
     * @memberof EggEventOutput
     */
    date: Date;
    /**
     * 
     * @type {Date}
     * @memberof EggEventOutput
     */
    createdDateTime: Date;
}

/**
 * Check if a given object implements the EggEventOutput interface.
 */
export function instanceOfEggEventOutput(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "amount" in value;
    isInstance = isInstance && "date" in value;
    isInstance = isInstance && "createdDateTime" in value;

    return isInstance;
}

export function EggEventOutputFromJSON(json: any): EggEventOutput {
    return EggEventOutputFromJSONTyped(json, false);
}

export function EggEventOutputFromJSONTyped(json: any, ignoreDiscriminator: boolean): EggEventOutput {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'amount': json['amount'],
        'date': (new Date(json['date'])),
        'createdDateTime': (new Date(json['created_date_time'])),
    };
}

export function EggEventOutputToJSON(value?: EggEventOutput | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'amount': value.amount,
        'date': (value.date.toISOString().substr(0,10)),
        'created_date_time': (value.createdDateTime.toISOString()),
    };
}

