/* tslint:disable */
/* eslint-disable */
/**
 * chicken-data API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EggEventInput
 */
export interface EggEventInput {
    /**
     * 
     * @type {number}
     * @memberof EggEventInput
     */
    amount: number;
    /**
     * 
     * @type {Date}
     * @memberof EggEventInput
     */
    date: Date;
}

/**
 * Check if a given object implements the EggEventInput interface.
 */
export function instanceOfEggEventInput(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "amount" in value;
    isInstance = isInstance && "date" in value;

    return isInstance;
}

export function EggEventInputFromJSON(json: any): EggEventInput {
    return EggEventInputFromJSONTyped(json, false);
}

export function EggEventInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): EggEventInput {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'amount': json['amount'],
        'date': (new Date(json['date'])),
    };
}

export function EggEventInputToJSON(value?: EggEventInput | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'amount': value.amount,
        'date': (value.date.toISOString().substr(0,10)),
    };
}

