/* tslint:disable */
/* eslint-disable */
/**
 * chicken-data API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const GroupByUnitInput = {
    Day: 'DAY',
    Month: 'MONTH',
    Year: 'YEAR'
} as const;
export type GroupByUnitInput = typeof GroupByUnitInput[keyof typeof GroupByUnitInput];


export function GroupByUnitInputFromJSON(json: any): GroupByUnitInput {
    return GroupByUnitInputFromJSONTyped(json, false);
}

export function GroupByUnitInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): GroupByUnitInput {
    return json as GroupByUnitInput;
}

export function GroupByUnitInputToJSON(value?: GroupByUnitInput | null): any {
    return value as any;
}

