/* tslint:disable */
/* eslint-disable */
/**
 * chicken-data API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TransactionEventOutput
 */
export interface TransactionEventOutput {
    /**
     * 
     * @type {number}
     * @memberof TransactionEventOutput
     */
    id: number;
    /**
     * 
     * @type {number}
     * @memberof TransactionEventOutput
     */
    amount: number;
    /**
     * 
     * @type {string}
     * @memberof TransactionEventOutput
     */
    note: string;
    /**
     * 
     * @type {Date}
     * @memberof TransactionEventOutput
     */
    date: Date;
    /**
     * 
     * @type {Date}
     * @memberof TransactionEventOutput
     */
    createdDateTime: Date;
}

/**
 * Check if a given object implements the TransactionEventOutput interface.
 */
export function instanceOfTransactionEventOutput(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "amount" in value;
    isInstance = isInstance && "note" in value;
    isInstance = isInstance && "date" in value;
    isInstance = isInstance && "createdDateTime" in value;

    return isInstance;
}

export function TransactionEventOutputFromJSON(json: any): TransactionEventOutput {
    return TransactionEventOutputFromJSONTyped(json, false);
}

export function TransactionEventOutputFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransactionEventOutput {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'amount': json['amount'],
        'note': json['note'],
        'date': json['date'],
        'createdDateTime': json['created_date_time'],
    };
}

export function TransactionEventOutputToJSON(value?: TransactionEventOutput | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'amount': value.amount,
        'note': value.note,
        'date': value.date,
        'created_date_time': value.createdDateTime,
    };
}

