/* tslint:disable */
/* eslint-disable */
/**
 * chicken-data API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TransactionEventInput
 */
export interface TransactionEventInput {
    /**
     * 
     * @type {number}
     * @memberof TransactionEventInput
     */
    amount: number;
    /**
     * 
     * @type {string}
     * @memberof TransactionEventInput
     */
    note: string;
    /**
     * 
     * @type {Date}
     * @memberof TransactionEventInput
     */
    date: Date;
}

/**
 * Check if a given object implements the TransactionEventInput interface.
 */
export function instanceOfTransactionEventInput(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "amount" in value;
    isInstance = isInstance && "note" in value;
    isInstance = isInstance && "date" in value;

    return isInstance;
}

export function TransactionEventInputFromJSON(json: any): TransactionEventInput {
    return TransactionEventInputFromJSONTyped(json, false);
}

export function TransactionEventInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransactionEventInput {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'amount': json['amount'],
        'note': json['note'],
        'date': json['date'],
    };
}

export function TransactionEventInputToJSON(value?: TransactionEventInput | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'amount': value.amount,
        'note': value.note,
        'date': value.date,
    };
}

